server:
  port: 8081
application:
  name: conta
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:~/credito
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2