server:
  port: 8080
application:
  name: conta
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:~/credito
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2

  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      group-id: credito
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.zupedu.credito.oferta.NovaContaDeserializer
      topic: NOVA_CONTA